name: pr-auto-update
on:
  push: {}

jobs:
  pr-auto-update:
    name: Automatic PR Updater
    runs-on: ubuntu-latest
    steps:
      - uses: CSSUoB/pr-auto-updater@conflict-tag
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          PR_FILTER: 'labelled'
          PR_LABELS: 'sync'
          MERGE_CONFLICT_ACTION: 'label'
          MERGE_CONFLICT_LABEL: 'conflict'
